# Generated by Django 3.2.5 on 2021-07-15 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms_app', '0007_login'),
    ]

    operations = [
        migrations.AddField(
            model_name='login',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
