# Generated by Django 3.2.5 on 2021-07-28 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms_app', '0014_alter_comment_post'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Login',
        ),
        migrations.DeleteModel(
            name='Signup',
        ),
        migrations.AddField(
            model_name='book',
            name='Discription',
            field=models.TextField(null=True),
        ),
    ]
