# Generated by Django 3.2.5 on 2021-08-11 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms_app', '0016_auto_20210804_1606'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='Discription',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='comment',
            name='body',
            field=models.TextField(verbose_name='Comment'),
        ),
    ]
