# Generated by Django 3.2.5 on 2021-08-11 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms_app', '0017_auto_20210811_2110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='status',
            field=models.CharField(blank=True, choices=[('availbel', 'availbel'), ('rental', 'rental'), ('sold', 'sold')], max_length=50, null=True),
        ),
    ]
