# Generated by Django 3.2.5 on 2021-08-11 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms_app', '0018_alter_book_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='photo_author',
            field=models.ImageField(blank=True, null=True, upload_to='photos/owners/'),
        ),
        migrations.AlterField(
            model_name='book',
            name='photo_book',
            field=models.ImageField(blank=True, null=True, upload_to='photos/books/'),
        ),
    ]
