# Generated by Django 3.2.5 on 2021-10-08 02:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lms_app', '0019_auto_20210811_2121'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
